spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ssgdb
    username: ssg_user
    password:
    sql-script-encoding: utf-8
    data: classpath:data.sql
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: INFO

server:
  port: 5555
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
